# Copyright 2022 NEC Corporation
# Released under the MIT license.
# https://opensource.org/licenses/mit-license.php
#
# SDE-IMPL-RECOMMENDED REST API サーバーのポート番号を指定します
ports:
    http: 3007

# SDE-IMPL-RECOMMENDED ログレベルを次のいずれかを設定します[none/debug/info]
loglevel: info

# SDE-MSA-PRIN 過負荷を回避する （MSA-PRIN-ID-02）
# SDE-IMPL-RECOMMENDED Backpressureの設定をします
backPressure:
    threshold: 100  # 同時実行数しきい値

catalog:
    base: http://localhost:3001/catalog
operator: 
    session: http://localhost:3000/operator/session/
notification:
    base: http://localhost:3004/notification
bookManage:
    search: http://localhost:3005/book-manage/search
    identity: http://localhost:3005/book-manage/identity
    cooperateRequest: http://localhost:3005/book-manage/cooperate/request
    cooperateRequestRelease: http://localhost:3005/book-manage/cooperate/request/release
    cooperateUser: http://localhost:3005/book-manage/cooperate/user

timezone: Asia/Tokyo
